### PR TITLE
Added cadence, speed and assistance level + new layout

### PR DESCRIPTION
**Pull request by NicholasRasi**
Now it is possible to display:

- cadence
- speed
- assistance level

### CODE REVIEW

**Comment by markdotai** [comment]
Wow this is awesome :) So cool that you worked out where those values are - makes me want to try it now! And I didn't even expect assistance level would be in there. A lot of people have been asking for cadence, so they will appreciate it :)

I'm not a GitHub expert, so I'll work out how to merge your work. And then make a new build for the Garmin App Store.

**Comment by markdotai** [comment]
With these extra values, I'm wondering if it's possible to have 2 data fields (separate ones in the app store) - whether the Garmin device end, and the Shimano e-bike end can both handle 2 Bluetooth connections at once. Then it would be possible to display different data in each field. Might have to try it and see ...

**Comment by NicholasRasi** [comment]
:smile: thank you.
Actually there are more information that you can get from the ble connection.

The data available from the 3 notifications are (at least):
- assistance mode
- current speed
- assistance level
- cadence
- traveling time
- traveling distance
- cumulative distance
- average speed
- maximum speed
- traveling ranges (eco, normal, high)

However, I don't think that other information are truly useful for the average user, but they are there.

> With these extra values, I'm wondering if it's possible to have 2 data fields (separate ones in the app store) - whether the Garmin device end, and the Shimano e-bike end can both handle 2 Bluetooth connections at once. Then it would be possible to display different data in each field. Might have to try it and see ...

This is possible because for example, with the Vivoactive 4 it is possible to add 2 fields on the same page. However I don't think is the best way to achieve a good result mainly because:
- users need to download and configure two apps
- energy waste due to multiple open connections.

I also tried to display the fields on multiple lines with a simple "\n" however it does not work.

I think that it would be better to use the [complex data field](https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/DataField.html), and  display the 3 values vertically. However, it requires more efforts.

**Comment by NicholasRasi** [comment]
Changelog:
- added a new layout based on [DataField](https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/DataField.html). It is implemented using [Dc (device context)](https://developer.garmin.com/connect-iq/api-docs/Toybox/Graphics/Dc.html), computing the position of elements at runtime, because as far as I know layouts are more memory intensive and it easy to get a out of memory error.
- the user can now choose among 4 values. The value will be displayed only if not off. In this way the datafield can be used also with other datafields on the same page (e.g. as a single field) depending on the user's configuration.
- refactoring of the code: the BLE section was moved to another file
- added mockup BLE: it can be used to simulate the BLE connection (now it just return random values). It can be switched on setting to true the ```debugging``` variable
- the label was removed to simplify the layout

I've tested it with the simulator and a Vivoactive 4 and it seems to work.

**Pull request merged**
